version: '3'

services:
  mongodb-primary:
    container_name: 'mongodb'
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest
    ports:
      - 27017:27017    
    volumes:
      - 'mongodb_data:/bitnami'
    networks:
      - minha_rede

  app:
    container_name: 'app-nestjs'
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app
    networks:
      - minha_rede
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - mongodb-primary
      # não use docker desktop (linux) ou (windows)

volumes:
  mongodb_data:
    driver: local

networks:
  minha_rede:
      name: minha_rede
      external: true